<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>ThreadPriorityApp</RootNamespace>
    <AssemblyName>ThreadPriorityApp</AssemblyName>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>
</Project>
